project:
  type: website
  output-dir: C:/Users/rankinai.stu/OneDrive - UBC/Documents/GitHub/E-Portfolio-sample

website:
  title: "Your E-Portfolio"
  theme: jekyll-theme-cayman
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: resume.qmd
        text: Resume
      - href: content.qmd
        text: Content & Deliverables

format:
  html:
    theme: flatly
    css: styles.css
    toc: true

editor: visual

