project:
  type: website
  output-dir: C:\Users\ranki\Documents\GitHub\E-Portfolio
website:
  title: "Aidan Villahermosa Rankin"
  navbar:
    right:
      - href: index.qmd
        text: Home
      - href: resume.qmd
        text: CV
      - href: project.qmd
        text: Capstone project
      - href: content.qmd
        text: Content & deliverables
      - href: other.qmd
        text: Other work

format:
  html:
    theme: 
      - brite
      - custom.scss
    email-obfuscation: javascript
    toc: true
    link-external-newwindow: true
    license: "CC BY-SA"


editor: visual

