---
title: "Resume"
---

# Education

**Honours Bachelor of Science, Biodiversity and Conservation Biology.**

*University of Toronto. 2023.*

-   Minors - Geographic Information Systems, Philosophy

-   Relevant coursework:

    -   

**Master of Geomatics for Environmental Management.**

*University of British Columbia. 2025.*

# Work Experience

**GIS Library Assistant**

University of Toronto Map and Data Library, May 2022-October 2023

-   Assisted with special GIS projects
-   Prepared geospatial data, including digitizing and georeferencing historical maps
-   Produced web maps for presentation and display

*Reports:*

-   List any non-peer reviewed materials you'd like to share here.

# Conferences & Talks

*Invited Talks*

-   If you've been invited to speak in a professional setting, list that here.

*Conference Presentations*

-   If the presentation was at a conference, list them here.

# Awards & Honors

-   List any scholarships, bursaries, etc.

# Teaching Assistantships

-   List any TA positions you may have held.

# Institutional Service

-   Volunteering etc.
